/** @type {import('tailwindcss').Config} */
export default {
  content: ['./resources/**/*.blade.php', './resources/**/*.js', './resources/**/*.ts'],
  theme: {
    extend: {
      colors: {
        // Reference CSS custom properties for colors
        'earth-deep': 'var(--color-earth-deep)',
        'earth-dark': 'var(--color-earth-dark)',
        'earth-mid': 'var(--color-earth-mid)',
        'earth-warm': 'var(--color-earth-warm)',
        'terracotta': 'var(--color-terracotta)',
        'terracotta-light': 'var(--color-terracotta-light)',
        'sand': 'var(--color-sand)',
        'sand-light': 'var(--color-sand-light)',
        'parchment': 'var(--color-parchment)',
        'bone': 'var(--color-bone)',
        'ink': 'var(--color-ink)',
        'ink-soft': 'var(--color-ink-soft)',
        'sage': 'var(--color-sage)',
        'sage-light': 'var(--color-sage-light)',
        // Semantic tokens
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'bg-tertiary': 'var(--bg-tertiary)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'accent-primary': 'var(--accent-primary)',
        'accent-secondary': 'var(--accent-secondary)',
      },
      spacing: {
        // Reference CSS custom properties for spacing
        '3xs': 'var(--space-3xs)',
        '2xs': 'var(--space-2xs)',
        'xs': 'var(--space-xs)',
        'sm': 'var(--space-sm)',
        'md': 'var(--space-md)',
        'lg': 'var(--space-lg)',
        'xl': 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
      },
      maxWidth: {
        'container': 'var(--container-width)',
        'container-narrow': 'var(--container-narrow)',
        'container-wide': 'var(--container-wide)',
        'prose': 'var(--container-prose)',
        'content-text': 'var(--content-max-text)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      fontFamily: {
        'display': 'var(--font-display)',
        'body': 'var(--font-body)',
        'accent': 'var(--font-accent)',
      },
      fontSize: {
        'xs': 'var(--text-xs)',
        'sm': 'var(--text-sm)',
        'base': 'var(--text-base)',
        'lg': 'var(--text-lg)',
        'xl': 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
        'massive': 'var(--text-massive)',
      },
      transitionDuration: {
        'fast': 'var(--duration-fast)',
        'normal': 'var(--duration-normal)',
        'slow': 'var(--duration-slow)',
        'slower': 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        'settle': 'var(--ease-settle)',
        'precise': 'var(--ease-precise)',
        'release': 'var(--ease-release)',
        'ambient': 'var(--ease-ambient)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('tailwindcss-animate'),
  ],
};
