<?php

declare(strict_types=1);

$GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] = '.*';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['sitename'] = 'Männerkreis Niederbayern/ Straubing';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['devIPmask'] = '';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['displayErrors'] = 0;
$GLOBALS['TYPO3_CONF_VARS']['BE']['debug'] = false;
$GLOBALS['TYPO3_CONF_VARS']['SYS']['reverseProxySSL'] = '*';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['reverseProxyIP'] = '*';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['trustedHostsPattern'] = '*';
$GLOBALS['TYPO3_CONF_VARS']['SYS']['reverseProxyHeaderMultiValue'] = 'first';

// ---------------------------------------------------------------------------
// Docker / Coolify: configure database from environment variables
// In DDEV the settings.php auto-generated by DDEV takes precedence.
// ---------------------------------------------------------------------------
if (getenv('TYPO3_DB_HOST')) {
    $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['Default'] = [
        'driver' => getenv('TYPO3_DB_DRIVER') ?: 'mysqli',
        'host' => getenv('TYPO3_DB_HOST'),
        'port' => (int) (getenv('TYPO3_DB_PORT') ?: 3306),
        'dbname' => getenv('TYPO3_DB_NAME') ?: 'typo3',
        'user' => getenv('TYPO3_DB_USER') ?: 'typo3',
        'password' => getenv('TYPO3_DB_PASSWORD') ?: '',
        'charset' => 'utf8mb4',
        'tableoptions' => [
            'charset' => 'utf8mb4',
            'collate' => 'utf8mb4_unicode_ci',
        ],
    ];
}

if (getenv('TYPO3_MAIL_TRANSPORT')) {
    $GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport'] = getenv('TYPO3_MAIL_TRANSPORT');

    if (getenv('TYPO3_MAIL_SMTP_SERVER')) {
        $GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_server'] = getenv('TYPO3_MAIL_SMTP_SERVER');
    }
    if (getenv('TYPO3_MAIL_SMTP_ENCRYPT')) {
        $GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_encrypt'] = getenv('TYPO3_MAIL_SMTP_ENCRYPT');
    }
    if (getenv('TYPO3_MAIL_SMTP_USERNAME')) {
        $GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_username'] = getenv('TYPO3_MAIL_SMTP_USERNAME');
    }
    if (getenv('TYPO3_MAIL_SMTP_PASSWORD')) {
        $GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_smtp_password'] = getenv('TYPO3_MAIL_SMTP_PASSWORD');
    }
}